# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
        ('Configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuid', models.IntegerField(default='')),
                ('dni', models.IntegerField(default='')),
                ('phoneNumberColl', models.CharField(default='', max_length=30)),
                ('phoneNumberCollTwo', models.CharField(default='', max_length=30)),
                ('addresColl', models.TextField(default='')),
                ('Typecomision', models.CharField(choices=[('Porcentaje', 'Porcentaje por operacion'), ('Monto', 'Monto fijo por operacion')], default='porcentaje', max_length=30)),
                ('comision', models.IntegerField(default='')),
                ('typeCollaborador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_tipoCollaborador')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserProfile.tb_profile')),
            ],
        ),
    ]
