# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(default='')),
                ('phoneNumberClient', models.CharField(default='', max_length=30)),
                ('phoneNumberClientTwo', models.CharField(default='', max_length=30)),
                ('addressClient', models.TextField(default='')),
                ('dateCreate', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='UserProfile.tb_profile')),
            ],
        ),
        migrations.CreateModel(
            name='tb_invoicer_header_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codInvoicer', models.IntegerField(default='')),
                ('dateCreate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tb_liquidation_client_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codLiquidation', models.IntegerField(default='')),
                ('dateLiquidation', models.DateField()),
                ('totalAmount', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='tb_type_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionType', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='tb_invoicer_header_client',
            name='liquidationClienteKf',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Client.tb_liquidation_client_header'),
        ),
    ]
