# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-03 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_client_web',
            name='FormaDeRegistro',
            field=models.CharField(default='Registro Web', max_length=30, null=True),
        ),
    ]
