# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Service', '0001_initial'),
        ('Configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_reservasWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTurn', models.DateField(default='')),
                ('HoraTurn', models.TimeField(default='')),
                ('mail', models.EmailField(default='', max_length=30)),
                ('nombre', models.CharField(default='', max_length=30)),
                ('telefono', models.CharField(default='', max_length=30)),
                ('servicioPrestar', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Service.tb_service')),
                ('statusTurn', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_status')),
            ],
        ),
    ]
