# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-02 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservasWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_reservasweb',
            name='TipoReservas',
            field=models.CharField(default='ReservaWeb', max_length=30, null=True),
        ),
    ]
