# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservasWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_reservasweb',
            name='description',
            field=models.CharField(blank=True, default='Sin Descripcion', max_length=30),
        ),
        migrations.AddField(
            model_name='tb_reservasweb',
            name='montoAPagar',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
