# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-02 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservasWeb', '0002_tb_reservasweb_tiporeservas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_reservasweb',
            name='TipoReservas',
            field=models.CharField(default='Reserva Web', max_length=30, null=True),
        ),
    ]
