# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservasWeb', '0005_auto_20180115_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_reservasweb',
            name='observaciones',
            field=models.TextField(default='Sin Obsevaciones', max_length=3000),
        ),
    ]
