# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_service',
            name='codService',
        ),
        migrations.AddField(
            model_name='tb_service',
            name='image',
            field=models.ImageField(default='', upload_to='productos/img/'),
        ),
    ]
