# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_auto_20170824_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_service',
            name='image',
            field=models.ImageField(default='', upload_to='servicios/img/'),
        ),
    ]
