# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configuracion', '0001_initial'),
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_egreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(default='')),
                ('descripcion', models.TextField(default='', max_length=3000)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('proveedor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Proveedores.tb_proveedor')),
                ('tipoEgreso', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_tipoEgreso')),
                ('tipoPago', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_formasDePago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tb_ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(default='')),
                ('descripcion', models.TextField(default='', max_length=3000)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('service', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Service.tb_service')),
                ('tipoIngreso', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_tipoIngreso')),
                ('tipoPago', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_formasDePago')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
