# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(default='', max_length=30)),
                ('mailUser', models.EmailField(default='', max_length=30)),
                ('birthdayDate', models.DateField()),
                ('tipoUser', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(default='', upload_to='users/avatar/')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
