# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-09 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_inflacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enero', models.IntegerField(default='', null=True)),
                ('Febrero', models.IntegerField(default='', null=True)),
                ('Marzo', models.IntegerField(default='', null=True)),
                ('Abril', models.IntegerField(default='', null=True)),
                ('Mayo', models.IntegerField(default='', null=True)),
                ('Junio', models.IntegerField(default='', null=True)),
                ('Julio', models.IntegerField(default='', null=True)),
                ('Agosto', models.IntegerField(default='', null=True)),
                ('Septiembre', models.IntegerField(default='', null=True)),
                ('Octubre', models.IntegerField(default='', null=True)),
                ('Noviembre', models.IntegerField(default='', null=True)),
                ('Diciembre', models.IntegerField(default='', null=True)),
                ('dateCreate', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
