# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-08 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_mail',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
