# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-08 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0002_auto_20180308_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_mail',
            name='Asunto',
            field=models.CharField(default='Multipoint - Eventos', max_length=30000, null=True),
        ),
        migrations.AlterField(
            model_name='tb_mail',
            name='Mailbody',
            field=models.TextField(default='', max_length=30000, null=True),
        ),
    ]
