# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Configuracion', '0001_initial'),
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProduct', models.CharField(default='', max_length=30)),
                ('descriptionProduct', models.CharField(default='', max_length=330)),
                ('priceList', models.IntegerField(default='')),
                ('priceCost', models.IntegerField(default='')),
                ('alertMinStock', models.IntegerField(default='')),
                ('image', models.ImageField(default='', upload_to='productos/img/')),
                ('dateCreate', models.DateField(auto_now=True)),
                ('proveedor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Proveedores.tb_proveedor')),
                ('tipoProducto', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_tipoProducto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
