# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_product',
            name='codProduct',
        ),
    ]
