# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Service', '0001_initial'),
        ('Configuracion', '0001_initial'),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTurn', models.DateField(default='')),
                ('extraInfoTurn', models.TextField(default='', max_length=300)),
                ('isPay', models.BooleanField(default=False)),
                ('montoAPagar', models.IntegerField(blank=True, default=0)),
                ('montoPagado', models.IntegerField(blank=True, default=0, null=True)),
                ('ingenico_id', models.TextField(default='None', max_length=3000)),
                ('PagoOnline', models.BooleanField(default=False)),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Client.tb_client')),
                ('servicioPrestar', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Service.tb_service')),
                ('statusTurn', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_status')),
                ('turn', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Configuracion.tb_turn_sesion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
